"""Here we will see current research happening in Trading market we will analyse differet research articles which can help us creating our own custom AI models to work as an assistant for us."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/00_core.ipynb 2
def say_hello(to):
    "Say hello to research and development"
    return f'Hello {to}!'

# %% ../nbs/00_core.ipynb 5
def foo(): pass
