project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    keep-md: true
  commonmark: default

website:
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    collapse-below: lg
    left:
      - text: "Blogs"
        href: blog/index.qmd
  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]